# Generated by Django 5.0.4 on 2024-04-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passsword',
            new_name='password',
        ),
    ]
