# Generated by Django 5.0.4 on 2024-05-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('mobile_no', models.IntegerField()),
                ('collage', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='profile')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
