# Generated by Django 5.0.4 on 2024-05-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='collage',
            new_name='college',
        ),
    ]
